apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: tap-gui-catalog-info
  description: A sample catalog for Backstage
  annotations:
    'backstage.io/techdocs-ref': dir:.
spec:
  targets:
    - ./groups/default-org.yaml
    - ./domains/platform-domain.yaml
    - https://dev.azure.com/doddatvmware/tap-lab-canary-app/_git/system-software-catalog?path=/catalog-info.yaml