apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: platform-domain
  description: Everything related to the Platform
  annotations:
    'backstage.io/techdocs-ref': dir:.
spec:
  owner: platform-team
