apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: canary
  description: Hello world style services that platform team can use to ensure operations of the platform.
spec:
  owner: platform-team
  domain: platform-domain
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: hello
  description: Simple spring-boot java app demonstrating hello world capability
  tags:
    - app-accelerator
    - java
    - spring
    - web
    - tanzu
  annotations:
    backstage.io/kubernetes-label-selector: app.kubernetes.io/part-of=hello
    backstage.io/source-location: url:https://dev.azure.com/doddatvmware/tap-lab-canary-app/_git/hello
spec:
  type: service
  lifecycle: production
  owner: platform-team
  system: canary
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: appsso-starter-java
  description: Simple spring-boot java app demonstrating TAP app sso capability
  tags:
    - app-accelerator
    - java
    - spring
    - web
    - tanzu
  annotations:
    backstage.io/kubernetes-label-selector: app.kubernetes.io/part-of=appsso-starter-java
    backstage.io/source-location: url:https://dev.azure.com/doddatvmware/tap-lab-canary-app/_git/appsso-starter-java
spec:
  type: service
  lifecycle: production
  owner: platform-team
  system: canary
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: emoji-inclusion
  description: Simple spring-boot java app bringing smiles to your face
  tags:
    - java
    - spring
    - web
    - tanzu
  annotations:
    backstage.io/kubernetes-label-selector: app.kubernetes.io/part-of=emoji-inclusion
    backstage.io/source-location: url:https://github.com/doddatpivotal/emoji-inclusion
    backstage.tanzu.vmware.com/group.default.dev-team-1: 'catalog.entities.read'
spec:
  type: service
  lifecycle: production
  owner: platform-team
  system: canary
